Fix D-Bus checks.
Check whether dbus-1 is installed before trying to get flags for it.
That way, if you don't have dbus-1 installed, you don't get pkg-config
errors printed.

Don't expect the shell to be able to run a command inside $() and have
the result expand to the standard output of that command; that's not a
feature present in all Bourne-compatible shells.  Use backquotes
instead.

If the user specified --enable-dbus, and dbus-1 wasn't found, fail -
they asked for D-Bus sniffing support, but we can't give it to them, so
let them know that they can't have what they want.  They either need to
install the package or stop specifying --enable-dbus.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11872,9 +11872,9 @@ fi
 	if test "x$PKGCONFIG" != "xno"; then
 		{ echo "$as_me:$LINENO: checking for D-Bus" >&5
 echo $ECHO_N "checking for D-Bus... $ECHO_C" >&6; }
-		DBUS_LIBS=$($PKGCONFIG --libs dbus-1)
-		DBUS_CFLAGS=$($PKGCONFIG --cflags dbus-1)
-		if test "x$DBUS_LIBS" != "x" -o "x$DBUS_CFLAGS" != "x"; then
+		if "$PKGCONFIG" dbus-1; then
+			DBUS_LIBS=`"$PKGCONFIG" --libs dbus-1`
+			DBUS_CFLAGS=`"$PKGCONFIG" --cflags dbus-1`
 
 cat >>confdefs.h <<\_ACEOF
 #define PCAP_SUPPORT_DBUS 1
@@ -11888,6 +11888,9 @@ echo "${ECHO_T}yes" >&6; }
 		else
 			{ echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6; }
+			{ { echo "$as_me:$LINENO: error: --enable-dbus was given, but the dbus-1 package is not installed" >&5
+echo "$as_me: error: --enable-dbus was given, but the dbus-1 package is not installed" >&2;}
+   { (exit 1); exit 1; }; }
 		fi
 	fi
 
