Oops, didn't run autoreconf, so some hacks of my own got checked in.
Some stuff I was doing got checked in because I didn't run autoreconf
after backing that stuff out.  Re-run autoreconf and check in the
results.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11225,7 +11225,7 @@ esac
 if test "${enable_bluetooth+set}" = set; then
   enableval=$enable_bluetooth;
 else
-  enable_bluetooth=ifavailable
+  enable_bluetooth=yes
 fi
 
 
@@ -11369,29 +11369,16 @@ _ACEOF
 echo "$as_me: Bluetooth sniffing is supported" >&6;}
 
 else
-
-		    if test "$enable_bluetooth" = "ifavailable"; then
-			{ echo "$as_me:$LINENO: Bluetooth sniffing is not supported; install bluez-lib devel to enable it" >&5
+  { echo "$as_me:$LINENO: Bluetooth sniffing is not supported; install bluez-lib devel to enable it" >&5
 echo "$as_me: Bluetooth sniffing is not supported; install bluez-lib devel to enable it" >&6;}
-		    else
-			{ { echo "$as_me:$LINENO: error: --enable-bluetooth was specified, but Bluetooth sniffing is not supported; install bluez-lib devel to enable it" >&5
-echo "$as_me: error: --enable-bluetooth was specified, but Bluetooth sniffing is not supported; install bluez-lib devel to enable it" >&2;}
-   { (exit 1); exit 1; }; }
-		    fi
 
 fi
 
 
 		;;
 	*)
-		if test "$enable_bluetooth" = "ifavailable"; then
-			{ echo "$as_me:$LINENO: no Bluetooth sniffing support implemented for $host_os" >&5
+		{ echo "$as_me:$LINENO: no Bluetooth sniffing support implemented for $host_os" >&5
 echo "$as_me: no Bluetooth sniffing support implemented for $host_os" >&6;}
-		else
-			{ { echo "$as_me:$LINENO: error: --enable-bluetooth was specified, but no Bluetooth sniffing support implemented for $host_os" >&5
-echo "$as_me: error: --enable-bluetooth was specified, but no Bluetooth sniffing support implemented for $host_os" >&2;}
-   { (exit 1); exit 1; }; }
-		fi
 		;;
 	esac
 
@@ -11402,7 +11389,7 @@ fi
 if test "${enable_canusb+set}" = set; then
   enableval=$enable_canusb;
 else
-  enable_canusb=ifavailable
+  enable_canusb=yes
 fi
 
 
@@ -11547,29 +11534,16 @@ _ACEOF
 echo "$as_me: canusb sniffing is supported" >&6;}
 
 else
-
-		    if test "$enable_canusb" = "ifavailable"; then
-			{ echo "$as_me:$LINENO: canusb sniffing is not supported; install libusb1.0 lib devel to enable it" >&5
+  { echo "$as_me:$LINENO: canusb sniffing is not supported; install libusb1.0 lib devel to enable it" >&5
 echo "$as_me: canusb sniffing is not supported; install libusb1.0 lib devel to enable it" >&6;}
-		    else
-			{ { echo "$as_me:$LINENO: error: --enable-canusb was given, but canusb sniffing is not supported; install libusb1.0 lib devel to enable it" >&5
-echo "$as_me: error: --enable-canusb was given, but canusb sniffing is not supported; install libusb1.0 lib devel to enable it" >&2;}
-   { (exit 1); exit 1; }; }
-		    fi
 
 fi
 
 
 		;;
 	*)
-		if test "$enable_canusb" = "ifavailable"; then
-			{ echo "$as_me:$LINENO: no canusb support implemented for $host_os" >&5
+		{ echo "$as_me:$LINENO: no canusb support implemented for $host_os" >&5
 echo "$as_me: no canusb support implemented for $host_os" >&6;}
-		else
-			{ { echo "$as_me:$LINENO: error: --enable-canusb was given, but no canusb support implemented for $host_os" >&5
-echo "$as_me: error: --enable-canusb was given, but no canusb support implemented for $host_os" >&2;}
-   { (exit 1); exit 1; }; }
-		fi
 		;;
 	esac
 
@@ -11580,45 +11554,77 @@ fi
 if test "${enable_can+set}" = set; then
   enableval=$enable_can;
 else
-  enable_can=ifavailable
+  enable_can=yes
 fi
 
 
 if test "x$enable_can" != "xno" ; then
 		case "$host_os" in
 	linux*)
-		#include <sys/socket.h>],
-	 -, _AC_CHECK_HEADER_OLD([linux/can.h],[
-		    AC_DEFINE(PCAP_SUPPORT_CAN, 1, [target host supports CAN sniffing])
-		    CAN_SRC=pcap-can-linux.c
-		    AC_MSG_NOTICE(CAN sniffing is supported)],[],
-		    if test "$enable_can" = "ifavailable"; then
-			AC_MSG_NOTICE([CAN sniffing is not supported])
-		    else
-			AC_MSG_ERROR([--enable-can was specified, but CANbus sniffing is not supported])
-		    fi
-		,#include <sys/socket.h>)],
-	      _AC_CHECK_HEADER_NEW([linux/can.h],[
-		    AC_DEFINE(PCAP_SUPPORT_CAN, 1, [target host supports CAN sniffing])
-		    CAN_SRC=pcap-can-linux.c
-		    AC_MSG_NOTICE(CAN sniffing is supported)],[],
-		    if test "$enable_can" = "ifavailable"; then
-			AC_MSG_NOTICE([CAN sniffing is not supported])
-		    else
-			AC_MSG_ERROR([--enable-can was specified, but CANbus sniffing is not supported])
-		    fi
-		,#include <sys/socket.h>)])
+		{ echo "$as_me:$LINENO: checking for linux/can.h" >&5
+echo $ECHO_N "checking for linux/can.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_linux_can_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <sys/socket.h>
+
+
+#include <linux/can.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_header_linux_can_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_header_linux_can_h=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_linux_can_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_can_h" >&6; }
+if test $ac_cv_header_linux_can_h = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define PCAP_SUPPORT_CAN 1
+_ACEOF
+
+			CAN_SRC=pcap-can-linux.c
+			{ echo "$as_me:$LINENO: CAN sniffing is supported" >&5
+echo "$as_me: CAN sniffing is supported" >&6;}
+else
+  { echo "$as_me:$LINENO: CAN sniffing is not supported" >&5
+echo "$as_me: CAN sniffing is not supported" >&6;}
+fi
+
 
 		;;
 	*)
-		if test "$enable_can" = "ifavailable"; then
-			{ echo "$as_me:$LINENO: no CAN sniffing support implemented for $host_os" >&5
+		{ echo "$as_me:$LINENO: no CAN sniffing support implemented for $host_os" >&5
 echo "$as_me: no CAN sniffing support implemented for $host_os" >&6;}
-		else
-			{ { echo "$as_me:$LINENO: error: --enable-can was specified, but no CAN sniffing support implemented for $host_os" >&5
-echo "$as_me: error: --enable-can was specified, but no CAN sniffing support implemented for $host_os" >&2;}
-   { (exit 1); exit 1; }; }
-		fi
 		;;
 	esac
 
